#%RAML 1.0 Library
usage:
types:
  flightRequest: !include /exchange_modules/7dfbd1f2-b078-48f3-b863-3d966ecd71ac/flightdatatype/1.0.0/flightdatatype.raml
  bookingRequest: !include /exchange_modules/7dfbd1f2-b078-48f3-b863-3d966ecd71ac/requestflightdatatype/1.0.0/requestflightdatatype.raml
  flightResponse: !include /exchange_modules/7dfbd1f2-b078-48f3-b863-3d966ecd71ac/responseflightdatatype/1.0.0/responseflightdatatype.raml
  bookingResponse: !include /exchange_modules/7dfbd1f2-b078-48f3-b863-3d966ecd71ac/userbookingdatatype/1.0.0/userbookingdatatype.raml
  