#%RAML 1.0 DataType

type: object
properties:
  status?:
      enum: [UPDATE,CANCEL,CREATE]
  departureFlight:
    type: object
    required: true
    properties:
      source?: string
      destination?: string
      name?: string
      price?: number
      time?: datetime-only
      flightID?: string
      bookingID?: string
      emailID: string
      user:
        type: array
        required: true
        items:
          type: !include userDataType.raml
  returnFlight:
    type: object
    required: false
    properties:
      source?: string
      destination?: string
      name?: string
      price?: number
      time?: datetime-only
      flightID?: string
      bookingID?: string
      emailID: string
      user:
        type: array
        required: true
        items:
          type: !include userDataType.raml