#%RAML 1.0 NamedExample

status: UPDATE
departureFlight:
    source: Mumbai
    destination: Delhi
    name: INDIGO
    price: 12000
    time: 2021-07-23T21:00:00
    flightID: IND0001
    emailID: abc@xyz.com
    bookingID: abc001
    user:
      -
        gender: Male
        firstName: Rakesh
        LastName: Jain
      -
        gender: Male
        firstName: Pankaj
        LastName: Jain

returnFlight:
    source: Delhi
    destination: Mumbai
    name: INDIGO
    price: 4500
    time: 2021-07-25T21:00:00
    flightID: IND0002
    emailID: abc@xyz.com
    bookingID: abc001
    user:
      -
        gender: Male
        firstName: Rakesh
        LastName: Jain
      -
        gender: Male
        firstName: Pankaj
        LastName: Jain
